language: cpp

git:
  submodules: false

before_install:
- sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) universe"
- sudo add-apt-repository -y ppa:zoogie/sdl2-snapshots
- sudo add-apt-repository -y ppa:openrave/release
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo add-apt-repository -y ppa:spvkgn/mediainfo 
- sudo apt-add-repository -y ppa:sfttech/random  # libepoxy
- sudo apt-get -qq update
- sudo apt-get -qq install pkg-config libtinyxml2-dev libepoxy-dev libunittest++-dev libsdl2-mixer-dev assimp-dev g++-4.8
- sudo ln -sf /usr/bin/g++-4.8 /usr/bin/g++
- sudo ln -sf /usr/lib/libassimp3.0.so /usr/lib/libassimp.so
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- git submodule update --init --depth 1

compiler:
- gcc
- clang

before_script:
- mkdir build && cd build

script:
- cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$PWD/install ..
- make install -j4
- make tests -j4
- ctest -j4

notifications:
  irc: "irc.freenode.com##glportal"
  use_notice: true
  skip_join: true